# Exercícios Python e Numpy

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos na aula de Python e Numpy. Sabemos que acabamos passando meio rápido durante a aula, então o objetivo aqui é conseguir treinar os conceitos para você conseguir usa-los na prática mais tarde.

Qualquer dúvida pode ficar a vontade para perguntar no Slack ou diretamente para gente, vamos ficar felizes em ajudar :)

## Python

Aqui na parte de Python vamos passar por algumas das principais coisas que você precisa saber, é claro que não colocamos tudo de importante da linguagem, só o mais necessário

### Variáveis

In [1]:
# Declare uma variavel chamada a e atribua o valor 10 a ela

In [2]:
# Imprime essa variavel que você acabou de criar

In [3]:
# Crie uma outra variavel b que recebe o valor de a so que como string

In [4]:
# Combine sua variavel b a variavel abaixo para obter a string "Hello 10" em uma variavel d
c = "Hello "

In [7]:
# Imprima a variável d

### Strings

In [14]:
my_str = 'Insira uma frase aqui!'

In [16]:
# Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)

In [17]:
# Crie uma lista "my_words" com cada palavra a frase

### Listas

In [8]:
lista = [1, 23, 31, 40, 56, 16]

In [9]:
# Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)

In [ ]:
# Faça um for que imprima o dobro de cada elemento da lista "lista" 

In [13]:
# Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension

In [10]:
# Crie uma nova lista chamada "pares"
# Faça um for que itetere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
# Imprima a lista "pares"

In [11]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [18]:
# Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())

#### Indexando

In [19]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [20]:
# Selecione o ultimo elemento da lista

In [21]:
# Selecione do primeiro até o 4 elemento da lista

In [22]:
# Selecione do segundo elemento da lista até o quinto

In [23]:
# Selecione do primeiro elemento da lista até o penultimo

### Dicionários

In [ ]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [35]:
# Crie um dicionario que contenha a contagem de cada elemento do vetor
my_dict = {}
#...

In [36]:
print(my_dict)

{}


### Funções

In [25]:
# Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    return 0

In [26]:
soma_elementos([1, 2, 3, 4, 5])

0

In [27]:
soma_elementos([-1, 5, 7, -2])

0

In [28]:
# Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip

In [29]:
produto_escalar([1, 2, 3], [0, 4, 7])

NameError: name 'produto_escalar' is not defined

In [ ]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

In [32]:
# Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par

In [ ]:
par_ou_impar(15)

In [ ]:
par_ou_impar(15)

In [33]:
# Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)

In [ ]:
diga_indice(['1', '2', '3'])

In [ ]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

In [37]:
# Importando a biblioteca
import numpy as np

### Arrays

In [39]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [40]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta

In [41]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb

In [43]:
# Crie um array de uns com shape (4, 5)

In [42]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)

In [72]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]

### Indexando

In [47]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[ 9  4  2 29 20 14 45 47 18 32  1  8 47 24 17]


In [48]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)

In [49]:
# Selecione todos os elementos maiores que 20

In [52]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [54]:
# Selecione o elemento na primeira linha da terceira coluna

In [53]:
# Selecione o elemento na primeira linha da ultima coluna

In [55]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]

In [ ]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]

In [56]:
# Selecione os elementos da ultima coluna inteira

In [57]:
# Selecione os elementos da 2a linha inteira

### Operações

In [50]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[7 2 1 0 0]


In [51]:
# Some 10 a todos os elementos de my_array

In [60]:
# Multiplique todos os elementos de my_array por 4

In [58]:
# Obtenha a soma de todos os elementos de my_array

In [59]:
# Obtenha a média de todos os elementos de my_array

In [69]:
# Obtenha o indice do maior elemento de my_array

In [61]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[5 7 4 3 6] 

[8 2 6 5 2]


In [64]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[1 9 3 6 3] 

[[4 5 1 7 4]
 [0 3 4 3 3]
 [5 4 9 1 2]
 [5 0 6 8 2]
 [0 3 9 9 9]
 [7 4 1 3 6]
 [9 0 5 4 9]
 [5 1 1 3 8]
 [2 3 7 6 0]
 [5 9 9 3 3]]


In [65]:
# Some my_array elemento por elemento em cada linha de my_other_array

In [66]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[9 7 6 6]
 [3 5 7 4]
 [6 8 4 6]
 [8 5 8 9]
 [2 1 5 7]] 

[[7 0 0 0 5]
 [7 7 7 2 9]
 [7 4 9 5 4]
 [5 4 7 0 4]
 [8 2 5 7 1]
 [3 0 3 8 2]
 [4 7 4 8 5]
 [8 2 6 9 6]
 [8 3 8 4 3]
 [6 7 9 8 2]]


In [67]:
# Faça a multiplicação entre my_other_array e my_array

In [73]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)

In [92]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[4 9 3 1]
 [9 1 5 5]
 [9 0 6 3]
 [1 4 1 3]
 [0 5 4 1]]


In [96]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)

In [97]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [98]:
# Gere a array anterior usando np.arange e a função reshape