# Tutorial de Numpy

Tutorial de numpy para Python 3.6

Pacote para operações numericas e cientificas.

Uma grande diferença entre lists e numpy's array é que não tem como adicionar novos elementos em um array. 

In [20]:
import numpy as np

In [21]:
# Transformando de list do python para array do numpy

a = [1, 2, 3, 4, 5]

l = np.array(a)

l

array([1, 2, 3, 4, 5])

### Operações vetoriais


In [22]:
# Como fazer operações vetoriais

l + 2

array([3, 4, 5, 6, 7])

### Matrixes

In [23]:
# Como criar uma matrix

b = np.array([[1,2,3],[4,5,6], [7, 8, 9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# Indexando normalmente
print(b[0][2])

# Indexamento menor
print(b[0, 2])

# Indexando com array
print(b[0, [1, 2]])

3
3
[2 3]


In [25]:
# Somando matrix com array

a = np.array([100, 200, 300])
b = np.array([[1,2,3],[4,5,6], [7, 8, 9]])

b + a

array([[101, 202, 303],
       [104, 205, 306],
       [107, 208, 309]])

In [26]:
# Multiplicação de matrixes

np.dot(b, b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])